AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI-powered RFP Response Agent - Master Template'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name for resource naming'
  
  SamApiKey:
    Type: String
    NoEcho: true
    Description: 'API key for SAM.gov access'
  
  CompanyName:
    Type: String
    Default: 'Your Company Name'
    Description: 'Company name for report templates'
  
  CompanyContact:
    Type: String
    Default: 'contact@yourcompany.com'
    Description: 'Company contact information'
  
  TemplatesBucketName:
    Type: String
    Description: 'S3 bucket containing the nested CloudFormation templates'
  
  TemplatesBucketPrefix:
    Type: String
    Default: 'cloudformation/'
    Description: 'Prefix for CloudFormation templates in the S3 bucket'
  
  BucketPrefix:
    Type: String
    Default: ''
    Description: 'Optional prefix for S3 bucket names to avoid conflicts'
  
  KnowledgeBaseId:
    Type: String
    Default: 'PLACEHOLDER'
    Description: 'ID of the Bedrock Knowledge Base for company information (use PLACEHOLDER for initial deployment)'

Resources:
  # Main Infrastructure Stack (S3 Buckets, SQS)
  MainInfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}core/main-template.yaml'
      Parameters:
        Environment: !Ref Environment
        SamApiKey: !Ref SamApiKey
        CompanyName: !Ref CompanyName
        CompanyContact: !Ref CompanyContact
        BucketPrefix: !Ref BucketPrefix
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

  # DynamoDB Tables Stack
  DynamoDbTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: MainInfrastructureStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}services/dynamodb-tables.yaml'
      Parameters:
        Environment: !Ref Environment
        BucketPrefix: !Ref BucketPrefix
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

  # Lambda Functions Stack
  LambdaFunctionsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - MainInfrastructureStack
      - DynamoDbTablesStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}services/lambda-functions.yaml'
      Parameters:
        Environment: !Ref Environment
        SamApiKey: !Ref SamApiKey
        CompanyName: !Ref CompanyName
        CompanyContact: !Ref CompanyContact
        SqsSamJsonMessagesQueueArn: !GetAtt MainInfrastructureStack.Outputs.SqsSamJsonMessagesQueueArn
        BucketPrefix: !Ref BucketPrefix
        KnowledgeBaseId: !Ref KnowledgeBaseId
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

  # EventBridge Rules Stack
  EventBridgeRulesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaFunctionsStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}services/eventbridge-rules.yaml'
      Parameters:
        Environment: !Ref Environment
        SamGovDailyDownloadFunctionArn: !GetAtt LambdaFunctionsStack.Outputs.SamGovDailyDownloadFunctionArn
        SamMergeAndArchiveResultLogsFunctionArn: !GetAtt LambdaFunctionsStack.Outputs.SamMergeAndArchiveResultLogsFunctionArn
        SamDailyEmailNotificationFunctionArn: !GetAtt LambdaFunctionsStack.Outputs.SamDailyEmailNotificationFunctionArn
        BucketPrefix: !Ref BucketPrefix
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

  # S3 Bucket Policies Stack
  S3BucketPoliciesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaFunctionsStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}services/s3-bucket-policies.yaml'
      Parameters:
        Environment: !Ref Environment
        SqsSamJsonMessagesQueueArn: !GetAtt MainInfrastructureStack.Outputs.SqsSamJsonMessagesQueueArn
        BucketPrefix: !Ref BucketPrefix
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

  # IAM Security Policies Stack
  IAMSecurityPoliciesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaFunctionsStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}core/iam-security-policies-simple.yaml'
      Parameters:
        Environment: !Ref Environment
        BucketPrefix: !Ref BucketPrefix
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

  # Monitoring and Alerting Stack
  MonitoringAlertingStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaFunctionsStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}services/monitoring-alerting.yaml'
      Parameters:
        Environment: !Ref Environment
        AlertEmail: !Ref CompanyContact
        BucketPrefix: !Ref BucketPrefix
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

  # S3 Event Notifications Stack
  S3EventNotificationsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - LambdaFunctionsStack
      - S3BucketPoliciesStack
      - IAMSecurityPoliciesStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}services/s3-event-notifications.yaml'
      Parameters:
        Environment: !Ref Environment
        SqsSamJsonMessagesQueueArn: !GetAtt MainInfrastructureStack.Outputs.SqsSamJsonMessagesQueueArn
        BucketPrefix: !Ref BucketPrefix
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

  # CloudFront UI Distribution Stack
  CloudFrontUIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: MainInfrastructureStack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucketName}.s3.amazonaws.com/${TemplatesBucketPrefix}services/cloudfront-ui.yaml'
      Parameters:
        Environment: !Ref Environment
        BucketPrefix: !Ref BucketPrefix
        UiBucketName: !GetAtt MainInfrastructureStack.Outputs.UiBucketName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'AI-RFP-Response-Agent'

Outputs:
  SamDataInBucketName:
    Description: 'Name of the SAM data input bucket'
    Value: !GetAtt MainInfrastructureStack.Outputs.SamDataInBucketName
    Export:
      Name: !Sub '${AWS::StackName}-SamDataInBucket'
  
  SamExtractedJsonResourcesBucketName:
    Description: 'Name of the extracted JSON resources bucket'
    Value: !GetAtt MainInfrastructureStack.Outputs.SamExtractedJsonResourcesBucketName
    Export:
      Name: !Sub '${AWS::StackName}-SamExtractedJsonResourcesBucket'
  
  SqsSamJsonMessagesQueueUrl:
    Description: 'URL of the SQS queue for JSON messages'
    Value: !GetAtt MainInfrastructureStack.Outputs.SqsSamJsonMessagesQueueUrl
    Export:
      Name: !Sub '${AWS::StackName}-SqsSamJsonMessagesQueue'
  
  SamGovDailyDownloadFunctionArn:
    Description: 'ARN of the SAM.gov daily download Lambda function'
    Value: !GetAtt LambdaFunctionsStack.Outputs.SamGovDailyDownloadFunctionArn
    Export:
      Name: !Sub '${AWS::StackName}-SamGovDailyDownloadFunction'
  
  SamJsonProcessorFunctionArn:
    Description: 'ARN of the JSON processor Lambda function'
    Value: !GetAtt LambdaFunctionsStack.Outputs.SamJsonProcessorFunctionArn
    Export:
      Name: !Sub '${AWS::StackName}-SamJsonProcessorFunction'
  
  SamProcessingKMSKeyArn:
    Description: 'ARN of the KMS key for SAM processing encryption'
    Value: !GetAtt IAMSecurityPoliciesStack.Outputs.SamProcessingKMSKeyArn
    Export:
      Name: !Sub '${AWS::StackName}-SamProcessingKMSKey'
  
  SamAlertsTopicArn:
    Description: 'ARN of the SNS topic for alerts'
    Value: !GetAtt MonitoringAlertingStack.Outputs.SamAlertsTopicArn
    Export:
      Name: !Sub '${AWS::StackName}-SamAlertsTopic'
  
  SamProcessingDashboardUrl:
    Description: 'URL of the CloudWatch dashboard'
    Value: !GetAtt MonitoringAlertingStack.Outputs.SamProcessingDashboardUrl
    Export:
      Name: !Sub '${AWS::StackName}-SamProcessingDashboard'
  
  CloudFrontDistributionId:
    Description: 'CloudFront distribution ID for the UI'
    Value: !GetAtt CloudFrontUIStack.Outputs.CloudFrontDistributionId
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'
  
  CloudFrontDistributionUrl:
    Description: 'CloudFront distribution URL for the UI'
    Value: !GetAtt CloudFrontUIStack.Outputs.CloudFrontDistributionUrl
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontUrl'