openapi: 3.0.3
info:
  title: RFP API Gateway
  version: 1.0.0
  description: |
    API Gateway for RFP Response Platform Lambda functions.
    Provides endpoints for workflow management, opportunities, and reports.
  contact:
    name: RFP Platform Team
    email: team@example.com

servers:
  - url: https://api.example.com/dev
    description: Development
  - url: https://api.example.com/prod
    description: Production

tags:
  - name: Dashboard
    description: Dashboard metrics and activity
  - name: Workflow
    description: Workflow orchestration
  - name: Opportunities
    description: Opportunity management
  - name: Reports
    description: Report generation and retrieval

paths:
  /dashboard/metrics:
    get:
      tags:
        - Dashboard
      summary: Get dashboard metrics
      operationId: getDashboardMetrics
      responses:
        '200':
          description: Dashboard metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardMetrics'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /dashboard/activity:
    get:
      tags:
        - Dashboard
      summary: Get recent activity
      operationId: getRecentActivity
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Recent activity list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /workflow/status:
    get:
      tags:
        - Workflow
      summary: Get workflow status
      operationId: getWorkflowStatus
      responses:
        '200':
          description: Current workflow status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStatus'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /opportunities:
    get:
      tags:
        - Opportunities
      summary: List opportunities
      operationId: listOpportunities
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of opportunities
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Opportunity'
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer
        '500':
          $ref: '#/components/responses/InternalServerError'

  /reports:
    get:
      tags:
        - Reports
      summary: List reports
      operationId: listReports
      responses:
        '200':
          description: List of generated reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    DashboardMetrics:
      type: object
      properties:
        totalOpportunities:
          type: integer
        matchedOpportunities:
          type: integer
        reportsGenerated:
          type: integer
        lastUpdated:
          type: string
          format: date-time

    Activity:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [download, process, match, report]
        status:
          type: string
          enum: [pending, success, failed]
        timestamp:
          type: string
          format: date-time
        message:
          type: string

    WorkflowStatus:
      type: object
      properties:
        currentStep:
          type: string
        status:
          type: string
          enum: [idle, running, completed, failed]
        lastRun:
          type: string
          format: date-time
        nextScheduled:
          type: string
          format: date-time

    Opportunity:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        postedDate:
          type: string
          format: date
        closeDate:
          type: string
          format: date
        matchScore:
          type: number
          format: float
          minimum: 0
          maximum: 1

    Report:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [web, user]
        generatedDate:
          type: string
          format: date-time
        downloadUrl:
          type: string
          format: uri

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object

  responses:
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []
